In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
routes = pd.read_csv("../hk_gtfs/routes.txt")

In [3]:
trips = pd.read_csv("../hk_gtfs/trips.txt")

In [4]:
stop_times = pd.read_csv("../hk_gtfs/stop_times.txt")

In [5]:
stops = pd.read_csv("../hk_gtfs/stops.txt")

In [6]:
calendar = pd.read_csv("../hk_gtfs/calendar.txt")
calendar_dates = pd.read_csv("../hk_gtfs/calendar_dates.txt")

In [7]:
frequencies = pd.read_csv("../hk_gtfs/frequencies.txt")

In [8]:
print(routes.head())

   route_id agency_id route_short_name  \
0      1001       KMB                1
1      1002       KMB               10
2      1006   KMB+CTB             102P
3      1008   KMB+CTB              103
4      1010   KMB+CTB              106

                              route_long_name  route_type  \
0               CHUK YUEN ESTATE - STAR FERRY           3
1          CHOI WAN - TAI KOK TSUI (CIRCULAR)           3
2                      SHAU KEI WAN - MEI FOO           3
3              CHUK YUEN ESTATE - POKFIELD RD           3
4  WONG TAI SIN - SIU SAI WAN (ISLAND RESORT)           3

                                           route_url
0  https://search.kmb.hk/KMBWebSite/?action=route...
1  https://search.kmb.hk/KMBWebSite/?action=route...
2  https://search.kmb.hk/KMBWebSite/?action=route...
3  https://search.kmb.hk/KMBWebSite/?action=route...
4  https://search.kmb.hk/KMBWebSite/?action=route...

In [9]:
stops.head()

,stop_id,stop_name,stop_lat,stop_lon,zone_id,location_type,stop_timezone
0,2,"[CTB] HIU TSUI STREET, SIU SAI WAN ROAD|[KMB+C...",22.26436,114.24821,2,0,Asia/Hong_Kong
1,3,"[CTB] FU SHING COURT, CHAI WAN ROAD|[KMB+CTB] ...",22.26578,114.24542,3,0,Asia/Hong_Kong
2,4,"[CTB] LOK HIN TERRACE, CHAI WAN ROAD|[KMB+CTB]...",22.26492,114.24167,4,0,Asia/Hong_Kong
3,5,"[CTB] WAN TSUI SHOPPING CENTRE, CHAI WAN ROAD|...",22.26312,114.23875,5,0,Asia/Hong_Kong
4,6,"[CTB] CHAK TSUI HOUSE WAN TSUI ESTATE, WAN TSU...",22.26242,114.23655,6,0,Asia/Hong_Kong

In [10]:
specific_routes = routes[(routes["route_short_name"] == "A10") & (routes["agency_id"] != "NLB")]
specific_routes

,route_id,agency_id,route_short_name,route_long_name,route_type,route_url
485,1671,CTB,A10,AP LEI CHAU (LEE LOK STREET) - AIRPORT (GROUND...,3,https://mobile.citybus.com.hk/nwp3/?f=1&ds=A10...

In [11]:
specific_trips = trips[trips["route_id"] == 1671]
print(specific_trips)
print(specific_trips.service_id.unique())

       route_id  service_id          trip_id
21462      1671         511  1671-1-511-0530
21463      1671         511  1671-1-511-0630
21464      1671         511  1671-1-511-2030
21465      1671         511  1671-2-511-0650
21466      1671         511  1671-2-511-0950
21467      1671         511  1671-2-511-1030
21468      1671         511  1671-2-511-2400
[511]

In [12]:
filtered_stoptimes = stop_times[stop_times["trip_id"] == "2006476-2-319-0710"]
filtered_stoptimes

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,timepoint
1097486,2006476-2-319-0710,07:10:00,07:10:00,20014536,1,0,1,1
1097487,2006476-2-319-0710,NaN,NaN,20011569,2,0,0,0
1097488,2006476-2-319-0710,NaN,NaN,20000136,3,0,0,0
1097489,2006476-2-319-0710,NaN,NaN,20020392,4,0,0,0
1097490,2006476-2-319-0710,NaN,NaN,20020393,5,0,0,0
1097491,2006476-2-319-0710,NaN,NaN,20014538,6,0,0,0
1097492,2006476-2-319-0710,NaN,NaN,20014539,7,0,0,0
1097493,2006476-2-319-0710,NaN,NaN,20014540,8,0,0,0
1097494,2006476-2-319-0710,NaN,NaN,20003404,9,0,0,0
1097495,2006476-2-319-0710,NaN,NaN,20014541,10,0,0,0
1097496,2006476-2-319-0710,NaN,NaN,20004544,11,0,0,0
1097497,2006476-2-319-0710,NaN,NaN,20002407,12,0,0,0
1097498,2006476-2-319-0710,NaN,NaN,20000008,13,0,0,0
1097499,2006476-2-319-0710,NaN,NaN,20000009,14,0,0,0
1097500,2006476-2-319-0710,NaN,NaN,20014542,15,0,0,0
1097501,2006476-2-319-0710,NaN,NaN,20011281,16,0,0,0
1097502,2006476-2-319-0710,07:37:00,07:37:00,20014524,17,1,0,1

filtered_stoptimes = stop_times[stop_times[trip_id"] == "1608-1-287-0600"]
filtered_stoptimes

In [13]:
filtered_stops = filtered_stoptimes.merge(stops[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']], on='stop_id', how='left')
filtered_stops

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,pickup_type,drop_off_type,timepoint,stop_name,stop_lat,stop_lon
0,2006476-2-319-0710,07:10:00,07:10:00,20014536,1,0,1,1,"SUN WUI ROAD, NEAR CAPITAL BUILDING",22.27767,114.18467
1,2006476-2-319-0710,NaN,NaN,20011569,2,0,0,0,"381 QUEEN'S ROAD EAST, OPPOSITE QUEEN ELIZABET...",22.27472,114.17879
2,2006476-2-319-0710,NaN,NaN,20000136,3,0,0,0,"QUEEN'S ROAD EAST, NEAR WAH YAN COLLEGE, HONG ...",22.27479,114.17603
3,2006476-2-319-0710,NaN,NaN,20020392,4,0,0,0,"KENNEDY ROAD, NEAR QUEEN'S ROAD EAST",22.27395,114.17522
4,2006476-2-319-0710,NaN,NaN,20020393,5,0,0,0,"KENNEDY ROAD, OUTSIDE GRANDVIEW TOWER",22.27268,114.17422
5,2006476-2-319-0710,NaN,NaN,20014538,6,0,0,0,"KENNEDY ROAD, NEAR CAMELOT HEIGHTS",22.27433,114.17106
6,2006476-2-319-0710,NaN,NaN,20014539,7,0,0,0,"KENNEDY ROAD, OPPPOSITE TO ST. FRANCIS CANOSSI...",22.27491,114.16840
7,2006476-2-319-0710,NaN,NaN,20014540,8,0,0,0,"KENNEDY ROAD, NEAR THE HONGKONG ELECTRIC CENTRE",22.27443,114.16564
8,2006476-2-319-0710,NaN,NaN,20003404,9,0,0,0,"KENNEDY ROAD, OUTSIDE OFFICE OF THE PRC MINIST...",22.27588,114.16145
9,2006476-2-319-0710,NaN,NaN,20014541,10,0,0,0,"KENNEDY ROAD, NEAR KENVILLE",22.27630,114.15949
10,2006476-2-319-0710,NaN,NaN,20004544,11,0,0,0,"CAINE ROAD, SHELLY STREET",22.28102,114.15218
11,2006476-2-319-0710,NaN,NaN,20002407,12,0,0,0,"POK FU LAM ROAD, EAST GATE OF THE UNIVERSITY O...",22.28384,114.13900
12,2006476-2-319-0710,NaN,NaN,20000008,13,0,0,0,"POK FU LAM ROAD, WEST GATE OF THE UNIVERSITY O...",22.28345,114.13652
13,2006476-2-319-0710,NaN,NaN,20000009,14,0,0,0,"POK FU LAM ROAD, OPPOSITE LADY HO TUNG HALL|PO...",22.28405,114.13369
14,2006476-2-319-0710,NaN,NaN,20014542,15,0,0,0,"SASSOON ROAD, NEAR THE UNIVERSITY OF HONG KONG...",22.26967,114.12999
15,2006476-2-319-0710,NaN,NaN,20011281,16,0,0,0,NEAR BAGUIO VILLA BLOCK 17|BAGUIO VILLAS (LOWE...,22.26196,114.13190
16,2006476-2-319-0710,07:37:00,07:37:00,20014524,17,1,0,1,BAGUIO VILLA (UPPER) MINIBUS TERMINUS,22.26226,114.13422

In [14]:
#the service id is equal to the days of the week in binary lol
#287 = regular weekdays
#319 = Weekdays + Saturday
#288 = Saturday
#448 = Sunday
#480 = Saturday, Sunday
#511 = all days
#Combinations: 287, 288, 448 or 319, 448
print(calendar[calendar.service_id == 480])
print(calendar_dates[calendar_dates.service_id == 448])

     service_id  monday  tuesday  wednesday  thursday  friday  saturday  \
479         480       0        0          0         0       0         1

     sunday  start_date  end_date
479       1    20200101  20991231
      service_id      date  exception_type
3808         448  20260101               1
3809         448  20260217               1
3810         448  20260218               1
3811         448  20260219               1
3812         448  20260403               1
3813         448  20260404               1
3814         448  20260406               1
3815         448  20260407               1
3816         448  20260501               1
3817         448  20260525               1
3818         448  20260619               1
3819         448  20260701               1
3820         448  20260926               1
3821         448  20261001               1
3822         448  20261019               1
3823         448  20261225               1
3824         448  20261226               1

In [15]:
frequencies[frequencies.trip_id == '8477-1-480-0900']

               trip_id start_time  end_time  headway_secs
34325  8477-1-480-0900   09:00:00  12:00:00          1800

In [16]:
def busroute_lookup(bus_number, company):
    specific_routes = routes[(routes["route_short_name"] == bus_number) & (routes["agency_id"] == company)]
    for row in specific_routes.itertuples():
        specific_trips = pd.merge(trips[trips["route_id"] == row.route_id], frequencies, on='trip_id', how="left")
        #specific_trips = trips[trips["route_id"] == row.route_id]
        print(specific_trips)
        filtered_stoptimes = stop_times[stop_times["trip_id"] == specific_trips["trip_id"].iloc[0]]
        filtered_stops = filtered_stoptimes.merge(stops[['stop_id', 'stop_name', 'stop_lat', 'stop_lon']], on='stop_id', how='left')
        print(filtered_stops[["stop_name"]])
        print(specific_trips.service_id.unique())

In [26]:
busroute_lookup("54", "GMB")

   route_id  service_id             trip_id start_time  end_time  headway_secs
0   2003174         511  2003174-1-511-1904   19:04:00  23:28:00           720
1   2003174         511  2003174-1-511-1604   16:04:00  19:04:00           360
2   2003174         511  2003174-1-511-0904   09:04:00  16:04:00           720
3   2003174         511  2003174-1-511-0540   05:40:00  09:04:00           360
4   2003174         511  2003174-2-511-1904   19:04:00  23:28:00           720
5   2003174         511  2003174-2-511-1604   16:04:00  19:04:00           360
6   2003174         511  2003174-2-511-0904   09:04:00  16:04:00           720
7   2003174         511  2003174-2-511-0540   05:40:00  09:04:00           360
                                            stop_name
0   SHUN ON ROAD, NEAR TIN WING HOUSE, SHUN TIN ES...
1         LEE ON ROAD WESTBOUND OUTSIDE LEE YIP HOUSE
2   LEE ON ROAD, NEAR LEE HANG HOUSE, SHUN LEE EST...
3   CLEAR WATER BAY ROAD, OUTSIDE TSUEN SHEK HOUSE...
4   CHOI HUNG ROAD, NEAR WING CHAI INDUSTRIAL BUIL...
5   SHATIN PASS ROAD, NEAR LUNG TAT HOUSE, LOWER W...
6   TUNG TAU TSUEN ROAD, NEAR LUNG MOON HOUSE, LOW...
7   FU MEI STREET WANG TAU HOM ESTATE, NEAR WANG F...
8   FU KEUNG STREET FU KEUNG COURT, NEAR FU YAT HOUSE
9   WANG TAU HOM CENTRAL ROAD, OPPOSITE TO LOK FU ...
10  WANG TAU HOM EAST ROAD MINIBUS BAY, NEAR WANG ...
[511]
   route_id  service_id             trip_id start_time  end_time  headway_secs
0   2003636         287  2003636-1-287-1755   17:55:00  19:54:00          1200
1   2003636         287  2003636-1-287-0950   09:50:00  09:54:00           900
2   2003636         287  2003636-1-287-0930   09:30:00  09:50:00          1200
3   2003636         287  2003636-1-287-0915   09:15:00  09:30:00           900
4   2003636         287  2003636-1-287-0855   08:55:00  09:15:00          1200
5   2003636         287  2003636-1-287-0840   08:40:00  08:55:00           900
6   2003636         287  2003636-1-287-0820   08:20:00  08:40:00          1200
7   2003636         287  2003636-1-287-0805   08:05:00  08:20:00           900
                                            stop_name
0   CENTRAL (CENTRAL FERRY PIERS)|CENTRAL FERRY PI...
1   CENTRAL STATION (CONNAUGHT ROAD CENTRAL), NEAR...
2   QUEEN'S ROAD WEST, OUTSIDE SHEK TONG TSUI MUNI...
3               BELCHER'S STREET, NEAR LUNGGA MANSION
4             BELCHER'S STREET, NEAR IMPERIAL KENNEDY
5          BELCHER'S STREET, NEAR LUEN WAI APARTMENTS
6                VICTORIA ROAD, OPPOSITE SERENE COURT
7        JUNCTION OF MT. DAVIS ROAD AND VICTORIA ROAD
8   MOUNT DAVIS ROAD OUTSIDE ST CLARE'S GIRLS' COL...
9            MOUNT DAVIS ROAD OUTSIDE GREENERY GARDEN
10                                QUEEN MARY HOSPITAL
11  POK FU LAM ROAD, OUTSIDE HONG KONG CHINESE CHR...
12          MOUNT DAVIS ROAD OPPOSITE GREENERY GARDEN
13  MOUNT DAVIS ROAD OPPOSITE ST CLARE'S GIRLS' CO...
14               VICTORIA ROAD, OUTSIDE REGENT HEIGHT
15       VICTORIA ROAD, OUTSIDE KENNEDY TOWN TERMINUS
16  CATCHICK STREET, OUTSIDE THE MERTON|CATCHICK S...
17         KENNEDY TOWN PRAYA, NEAR SAI CHEUNG STREET
18  DES VOEUX ROAD WEST, OPPOSITE KWAN YICK BUILDI...
19  CONNAUGHT ROAD WEST, OUTSIDE SUN YAT SEN MEMOR...
20  CONNAUGHT ROAD CENTRAL, OUTSIDE SHUN TAK CENTR...
21  PIER ROAD OPPOSITE TO HARBOUR BUILDING|PIER RO...
22                     MAN YIU STREET OUTSIDE TWO IFC
23  CENTRAL (CENTRAL FERRY PIERS)|CENTRAL FERRY PI...
[287]
    route_id  service_id             trip_id start_time  end_time  \
0    2003637         511  2003637-1-511-0955   09:55:00  22:25:00
1    2003637         511  2003637-1-511-0950   09:50:00  09:55:00
2    2003637         511  2003637-1-511-0930   09:30:00  09:50:00
3    2003637         511  2003637-1-511-0915   09:15:00  09:30:00
4    2003637         511  2003637-1-511-0855   08:55:00  09:15:00
5    2003637         511  2003637-1-511-0840   08:40:00  08:55:00
6    2003637         511  2003637-1-511-0820   08:20:00  08:40:00
7    2003637         511  2003637-1-511-0805   08:05:00  08:20:00
8    2003637         511  2003637-1-511-0745   07:45:00  08:05:00
9    2003637         511  2003637-1-511-0730   07:30:00  07:45:00
10   2003637         511  2003637-1-511-0710   07:10:00  07:30:00
11   2003637         511  2003637-1-511-0655   06:55:00  07:10:00

    headway_secs
0           1200
1            900
2           1200
3            900
4           1200
5            900
6           1200
7            900
8           1200
9            900
10          1200
11           900
                                            stop_name
0   CENTRAL (CENTRAL FERRY PIERS)|CENTRAL FERRY PI...
1   CENTRAL STATION (CONNAUGHT ROAD CENTRAL), NEAR...
2   QUEEN'S ROAD WEST, OUTSIDE SHEK TONG TSUI MUNI...
3               BELCHER'S STREET, NEAR LUNGGA MANSION
4             BELCHER'S STREET, NEAR IMPERIAL KENNEDY
5          BELCHER'S STREET, NEAR LUEN WAI APARTMENTS
6                VICTORIA ROAD, OPPOSITE SERENE COURT
7        JUNCTION OF MT. DAVIS ROAD AND VICTORIA ROAD
8   MOUNT DAVIS ROAD OUTSIDE ST CLARE'S GIRLS' COL...
9            MOUNT DAVIS ROAD OUTSIDE GREENERY GARDEN
10                                QUEEN MARY HOSPITAL
11  POK FU LAM ROAD, OUTSIDE HONG KONG CHINESE CHR...
12          MOUNT DAVIS ROAD OPPOSITE GREENERY GARDEN
13  MOUNT DAVIS ROAD OPPOSITE ST CLARE'S GIRLS' CO...
14               VICTORIA ROAD, OUTSIDE REGENT HEIGHT
15       VICTORIA ROAD, OUTSIDE KENNEDY TOWN TERMINUS
16  CATCHICK STREET, OUTSIDE THE MERTON|CATCHICK S...
17         KENNEDY TOWN PRAYA, NEAR SAI CHEUNG STREET
18  DES VOEUX ROAD WEST, OPPOSITE KWAN YICK BUILDI...
19  CONNAUGHT ROAD WEST, OUTSIDE SUN YAT SEN MEMOR...
20  CONNAUGHT ROAD CENTRAL, OUTSIDE SHUN TAK CENTR...
21  PIER ROAD OPPOSITE TO HARBOUR BUILDING|PIER RO...
22           CONNAUGHT PLACE, OUTSIDE EXCHANGE SQUARE
23                     MAN YIU STREET OUTSIDE TWO IFC
24  CENTRAL (CENTRAL FERRY PIERS)|CENTRAL FERRY PI...
[511]
   route_id  service_id             trip_id start_time  end_time  headway_secs
0   2009840         511  2009840-1-511-0630   06:30:00  07:00:00           900
                                            stop_name
0                                 QUEEN MARY HOSPITAL
1           MOUNT DAVIS ROAD OPPOSITE GREENERY GARDEN
2   MOUNT DAVIS ROAD OPPOSITE ST CLARE'S GIRLS' CO...
3                VICTORIA ROAD, OUTSIDE REGENT HEIGHT
4        VICTORIA ROAD, OUTSIDE KENNEDY TOWN TERMINUS
5   CATCHICK STREET, OUTSIDE THE MERTON|CATCHICK S...
6          KENNEDY TOWN PRAYA, NEAR SAI CHEUNG STREET
7   DES VOEUX ROAD WEST, OPPOSITE KWAN YICK BUILDI...
8   CONNAUGHT ROAD WEST, OUTSIDE SUN YAT SEN MEMOR...
9   CONNAUGHT ROAD CENTRAL, OUTSIDE SHUN TAK CENTR...
10  PIER ROAD OPPOSITE TO HARBOUR BUILDING|PIER RO...
11           CONNAUGHT PLACE, OUTSIDE EXCHANGE SQUARE
12                     MAN YIU STREET OUTSIDE TWO IFC
13  CENTRAL (CENTRAL FERRY PIERS)|CENTRAL FERRY PI...
[511]
   route_id  service_id             trip_id start_time  end_time  headway_secs
0   2009842         511  2009842-1-511-2245   22:45:00  23:25:00          1200
                                            stop_name
0   CENTRAL (CENTRAL FERRY PIERS)|CENTRAL FERRY PI...
1   CENTRAL STATION (CONNAUGHT ROAD CENTRAL), NEAR...
2   QUEEN'S ROAD WEST, OUTSIDE SHEK TONG TSUI MUNI...
3               BELCHER'S STREET, NEAR LUNGGA MANSION
4             BELCHER'S STREET, NEAR IMPERIAL KENNEDY
5          BELCHER'S STREET, NEAR LUEN WAI APARTMENTS
6                VICTORIA ROAD, OPPOSITE SERENE COURT
7        JUNCTION OF MT. DAVIS ROAD AND VICTORIA ROAD
8   MOUNT DAVIS ROAD OUTSIDE ST CLARE'S GIRLS' COL...
9            MOUNT DAVIS ROAD OUTSIDE GREENERY GARDEN
10                                QUEEN MARY HOSPITAL
[511]